import {Outfit} from "next/font/google";
import "./globals.scss";
import StateContextProvider from "@/context/StateContext";
import MenuLayout from "@/components/common/Menu/_MenuLayout";

const inter = Outfit({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="pl">
        <body className={`${inter.className} relative`}>
        <StateContextProvider>
            <MenuLayout/>
            {children}
        </StateContextProvider>
        </body>
        </html>
    );
}
